In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('https://media.githubusercontent.com/media/musthave-ML10/data_source/main/car.csv')

In [4]:
df.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner     mileage   engine   max_power  \
0  Individual       Manual   First Owner   23.4 kmpl  1248 CC      74 bhp   
1  Individual       Manual  Second Owner  21.14 kmpl  1498 CC  103.52 bhp   
2  Individual       Manual   Third Owner   17.7 kmpl  1497 CC      78 bhp   
3  Individual       Manual   First Owner   23.0 kmpl  1396 CC      90 bhp   
4  Individual       Manual   First Owner   16.1 kmpl  1298 CC    88.2 bhp   

                     torque  seats  
0            190Nm@ 2000rpm    5.0  
1       250Nm@ 1500-2500rpm    5.0  
2     12.7@ 2,700(kgm@ rpm)    5.0  
3  22.4 kgm at 1750-2750rpm    5.0  
4     11.5@ 4,500(kgm@ rpm)    5.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
name             8128 non-null object
year             8128 non-null int64
selling_price    8128 non-null int64
km_driven        8128 non-null int64
fuel             8128 non-null object
seller_type      8128 non-null object
transmission     8128 non-null object
owner            8128 non-null object
mileage          7907 non-null object
engine           7907 non-null object
max_power        7913 non-null object
torque           7906 non-null object
seats            7907 non-null float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB


In [6]:
round(df.describe(),2)

year  selling_price   km_driven    seats
count  8128.00        8128.00     8128.00  7907.00
mean   2013.80      638271.81    69819.51     5.42
std       4.04      806253.40    56550.55     0.96
min    1983.00       29999.00        1.00     2.00
25%    2011.00      254999.00    35000.00     5.00
50%    2015.00      450000.00    60000.00     5.00
75%    2017.00      675000.00    98000.00     5.00
max    2020.00    10000000.00  2360457.00    14.00

In [7]:
df['engine'].str.split(expand=True)

0    1
0     1248   CC
1     1498   CC
2     1497   CC
3     1396   CC
4     1298   CC
5     1197   CC
6     1061   CC
7      796   CC
8     1364   CC
9     1399   CC
10    1461   CC
11     993   CC
12    1248   CC
13     NaN  NaN
14    1061   CC
15    1198   CC
16    1248   CC
17    1396   CC
18     796   CC
19    1396   CC
20    1461   CC
21    1498   CC
22    1248   CC
23    1248   CC
24    1199   CC
25    1197   CC
26     796   CC
27    1248   CC
28    1061   CC
29     796   CC
...    ...  ...
8098  1248   CC
8099  2179   CC
8100  1497   CC
8101  1248   CC
8102  1582   CC
8103   NaN  NaN
8104  1497   CC
8105  1343   CC
8106  1582   CC
8107  1461   CC
8108  1493   CC
8109  1498   CC
8110   998   CC
8111  1364   CC
8112  1498   CC
8113  2494   CC
8114   796   CC
8115   796   CC
8116   998   CC
8117  1248   CC
8118  1197   CC
8119   998   CC
8120  1086   CC
8121   998   CC
8122  1396   CC
8123  1197   CC
8124  1493   CC
8125  1248   CC
8126  1396   CC
8127  1396   CC

[8128 rows x 2 columns]

In [8]:
df[['engine','engine_unit']] = df['engine'].str.split(expand=True)

In [9]:
df['engine'].head()

0    1248
1    1498
2    1497
3    1396
4    1298
Name: engine, dtype: object

In [10]:
df['engine'] = df['engine'].astype('float32')

In [11]:
df['engine'].head()

0    1248.0
1    1498.0
2    1497.0
3    1396.0
4    1298.0
Name: engine, dtype: float32

In [12]:
df['engine_unit'].unique()

array(['CC', nan], dtype=object)

In [13]:
df.drop('engine_unit', axis=1, inplace=True)

In [14]:
df[['max_power','max_power_unit']] = df['max_power'].str.split(expand=True)

In [15]:
df['max_power'].head()

0        74
1    103.52
2        78
3        90
4      88.2
Name: max_power, dtype: object

In [16]:
df['max_power'] = df['max_power'].astype('float32')

ValueError: could not convert string to float: 'bhp'

In [17]:
df[df['max_power'] =='bhp']

name  year  selling_price  km_driven fuel seller_type  \
4933  Maruti Omni CNG  2000          80000     100000  CNG  Individual   

     transmission         owner     mileage  engine max_power torque  seats  \
4933       Manual  Second Owner  10.9 km/kg   796.0       bhp    NaN    8.0   

     max_power_unit  
4933           None

In [18]:
def isFloat(value):
    try:
        num = float(value)
        return num
    except ValueError:
        return np.NaN

In [19]:
df['max_power'] = df['max_power'].apply(isFloat)

In [20]:
df['max_power_unit'].unique()

array(['bhp', nan, None], dtype=object)

In [21]:
df.drop('max_power_unit',  axis=1, inplace=True)

In [22]:
df[['mileage','mileage_unit']] = df['mileage'].str.split(expand=True)

In [23]:
df['mileage'] = df['mileage'].astype('float32')

In [24]:
df['mileage_unit'].unique()

array(['kmpl', 'km/kg', nan], dtype=object)

In [25]:
df['fuel'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [26]:
def mile(x):
    if x['fuel'] =='Petrol':
        return x['mileage']/ 80.43
    elif x['fuel'] =='Diesel':
        return x['mileage'] / 73.56
    elif x['fuel'] =='LPG':
        return x['mileage'] / 40.85
    else:
        return x['mileage'] / 44.23

In [27]:
df['mileage'] = df.apply(mile, axis=1)

In [28]:
df.drop('mileage_unit',axis=1,inplace=True)

In [29]:
df['torque'].head()

0              190Nm@ 2000rpm
1         250Nm@ 1500-2500rpm
2       12.7@ 2,700(kgm@ rpm)
3    22.4 kgm at 1750-2750rpm
4       11.5@ 4,500(kgm@ rpm)
Name: torque, dtype: object

In [30]:
df['torque']= df['torque'].str.upper()

In [31]:
def torque_unit(x):
    if 'NM' in str(x):
        return 'Nm'
    elif 'KGM' in str(x):
        return 'kgm'

In [32]:
df['torque_unit'] = df['torque'].apply(torque_unit)

In [33]:
df['torque_unit'].unique()

array(['Nm', 'kgm', None], dtype=object)

In [34]:
df['torque_unit'].isna()
df[df['torque_unit'].isna()]
df[df['torque_unit'].isna()]['torque'].unique()

array([nan, '250@ 1250-5000RPM', '510@ 1600-2400', '110(11.2)@ 4800',
       '210 / 1900'], dtype=object)

In [35]:
df[df['torque_unit'].isna()]['torque'].unique()

array([nan, '250@ 1250-5000RPM', '510@ 1600-2400', '110(11.2)@ 4800',
       '210 / 1900'], dtype=object)

In [36]:
df['torque_unit'].fillna('Nm',inplace=True)

In [42]:
def split_num(x):
    x = str(x)
    for i,j in enumerate(x):
        if j not in '0123456789.':
            cut = i
            break
    return x[:cut]

In [43]:
df['torque'] = df['torque'].apply(split_num)

In [44]:
df['torque']

0          190
1          250
2         12.7
3         22.4
4         11.5
5       113.75
6          7.8
7           59
8          170
9          160
10         248
11          78
12         190
13            
14          84
15         115
16         200
17        22.4
18          62
19       219.7
20         160
21         200
22         190
23         200
24         114
25         115
26          69
27       172.5
28          84
29          59
         ...  
8098       190
8099       330
8100       260
8101       197
8102     259.8
8103          
8104      13.5
8105      11.3
8106     259.8
8107       200
8108       250
8109       215
8110        90
8111       170
8112       215
8113      20.4
8114        62
8115        59
8116        90
8117       190
8118     113.7
8119        90
8120      96.1
8121        90
8122     219.7
8123     113.7
8124        24
8125       190
8126       140
8127       140
Name: torque, Length: 8128, dtype: object

In [45]:
df['torque'] = df['torque'].astype('float64')

ValueError: could not convert string to float: 

In [46]:
df['torque'] = df['torque'].replace('', np.NaN)

In [47]:
df['torque'] = df['torque'].astype('float64')

In [48]:
df['torque'].head()

0    190.0
1    250.0
2     12.7
3     22.4
4     11.5
Name: torque, dtype: float64

In [50]:
def torque_trans(x):
    if x['torque_unit'] =='kgm':
        return x['torque']*9.8066
    else:
        return x['torque']

In [51]:
df['torque'] = df.apply(torque_trans, axis=1)

In [52]:
df.drop('torque_unit',axis=1, inplace=True)

In [53]:
df.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner   mileage  engine  max_power  \
0  Individual       Manual   First Owner  0.318108  1248.0      74.00   
1  Individual       Manual  Second Owner  0.287384  1498.0     103.52   
2  Individual       Manual   Third Owner  0.220067  1497.0      78.00   
3  Individual       Manual   First Owner  0.312670  1396.0      90.00   
4  Individual       Manual   First Owner  0.200174  1298.0      88.20   

      torque  seats  
0  190.00000    5.0  
1  250.00000    5.0  
2  124.54382    5.0  
3  219.66784    5.0  
4  112.77590    5.0

In [54]:
df['name'] = df['name'].str.split(expand=True)[0]

In [56]:
df['name'].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Fiat', 'Datsun', 'Jeep',
       'Mercedes-Benz', 'Mitsubishi', 'Audi', 'Volkswagen', 'BMW',
       'Nissan', 'Lexus', 'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo',
       'Kia', 'Force', 'Ambassador', 'Ashok', 'Isuzu', 'Opel', 'Peugeot'],
      dtype=object)

In [57]:
df['name'] = df['name'].replace('Land','Land Rover')

In [58]:
df.isna().mean()

name             0.000000
year             0.000000
selling_price    0.000000
km_driven        0.000000
fuel             0.000000
seller_type      0.000000
transmission     0.000000
owner            0.000000
mileage          0.027190
engine           0.027190
max_power        0.026575
torque           0.027313
seats            0.027190
dtype: float64

In [59]:
df.dropna(inplace=True)
len(df)

7906

In [60]:
df = pd.get_dummies(df, columns = ['name','fuel','seller_type','transmission','owner'], drop_first=True)

In [62]:
df.head()

year  selling_price  km_driven   mileage  engine  max_power     torque  \
0  2014         450000     145500  0.318108  1248.0      74.00  190.00000   
1  2014         370000     120000  0.287384  1498.0     103.52  250.00000   
2  2006         158000     140000  0.220067  1497.0      78.00  124.54382   
3  2010         225000     127000  0.312670  1396.0      90.00  219.66784   
4  2007         130000     120000  0.200174  1298.0      88.20  112.77590   

   seats  name_Ashok  name_Audi        ...          fuel_Diesel  fuel_LPG  \
0    5.0           0          0        ...                    1         0   
1    5.0           0          0        ...                    1         0   
2    5.0           0          0        ...                    0         0   
3    5.0           0          0        ...                    1         0   
4    5.0           0          0        ...                    0         0   

   fuel_Petrol  seller_type_Individual  seller_type_Trustmark Dealer  \
0            0                       1                             0   
1            0                       1                             0   
2            1                       1                             0   
3            0                       1                             0   
4            1                       1                             0   

   transmission_Manual  owner_Fourth & Above Owner  owner_Second Owner  \
0                    1                           0                   0   
1                    1                           0                   1   
2                    1                           0                   0   
3                    1                           0                   0   
4                    1                           0                   0   

   owner_Test Drive Car  owner_Third Owner  
0                     0                  0  
1                     0                  0  
2                     0                  1  
3                     0                  0  
4                     0                  0  

[5 rows x 48 columns]

In [70]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('selling_price', axis=1), df['selling_price'],test_size=0.2, random_state=100)

In [72]:
from sklearn.ensemble import RandomForestRegressor

In [73]:
model = RandomForestRegressor(random_state=100)

In [74]:
model.fit(X_train, y_train)
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)

In [75]:
from sklearn.metrics import mean_squared_error
print("train_rmse:", mean_squared_error(y_train, train_pred)**0.5, "test_rsme:", mean_squared_error(y_test, test_pred)**0.5)

train_rmse: 60091.23988811351 test_rsme: 132476.64010840387


In [76]:
from sklearn.model_selection import KFold

In [77]:
df

year  selling_price  km_driven   mileage  engine  max_power     torque  \
0     2014         450000     145500  0.318108  1248.0      74.00  190.00000   
1     2014         370000     120000  0.287384  1498.0     103.52  250.00000   
2     2006         158000     140000  0.220067  1497.0      78.00  124.54382   
3     2010         225000     127000  0.312670  1396.0      90.00  219.66784   
4     2007         130000     120000  0.200174  1298.0      88.20  112.77590   
5     2017         440000      45000  0.250404  1197.0      81.86  113.75000   
6     2007          96000     175000  0.423501  1061.0      57.50   76.49148   
7     2001          45000       5000  0.200174   796.0      37.00   59.00000   
8     2011         350000      90000  0.320691  1364.0      67.10  170.00000   
9     2013         200000     169000  0.271887  1399.0      68.10  160.00000   
10    2014         500000      68000  0.258428  1461.0     108.45  248.00000   
11    2005          92000     100000  0.215094   993.0      60.00   78.00000   
12    2009         280000     140000  0.262371  1248.0      73.90  190.00000   
14    2009         180000      90000  0.234987  1061.0      67.00   84.00000   
15    2016         400000      40000  0.225662  1198.0      82.00  115.00000   
16    2016         778000      70000  0.333333  1248.0      88.50  200.00000   
17    2012         500000      53000  0.312670  1396.0      90.00  219.66784   
18    2002         150000      80000  0.244933   796.0      46.30   62.00000   
19    2016         680000     100000  0.306417  1396.0      88.73  219.70000   
20    2011         174000     100000  0.285481  1461.0      64.10  160.00000   
21    2017         950000      50000  0.346656  1498.0      98.60  200.00000   
22    2015         525000      40000  0.361474  1248.0      74.00  190.00000   
23    2012         600000      72000  0.292278  1248.0      88.80  200.00000   
24    2018         500000      35000  0.252393  1199.0      83.81  114.00000   
25    2016         575000      45000  0.266070  1197.0      83.10  115.00000   
26    2017         275000      28000  0.307099   796.0      47.30   69.00000   
27    2013         300000      70000  0.247417  1248.0      73.80  172.50000   
28    2009         220000     120000  0.234987  1061.0      67.00   84.00000   
29    2018         254999      25000  0.208877   796.0      34.20   59.00000   
30    2017         670000      70000  0.330343  1248.0      88.50  200.00000   
...    ...            ...        ...       ...     ...        ...        ...   
8097  2018         880000      65000  0.312670  1498.0      98.96  205.00000   
8098  2009         307000     100000  0.241979  1248.0      75.00  190.00000   
8099  2013         750000     120000  0.205275  2179.0     140.00  330.00000   
8100  2018         800000      85000  0.292278  1497.0     108.50  260.00000   
8101  2012         450000      70000  0.275965  1248.0      75.00  197.00000   
8102  2011         450000     128000  0.303426  1582.0     126.32  259.80000   
8104  2006         160000      70000  0.210121  1497.0     100.00  132.38910   
8105  2004         135000     120000  0.161631  1343.0      90.00  110.81458   
8106  2012         450000     128000  0.303426  1582.0     126.32  259.80000   
8107  2013         325000     100000  0.278004  1461.0      83.80  200.00000   
8108  2019        1575000      20000  0.241979  1493.0     113.40  250.00000   
8109  2018         750000      24000  0.331702  1498.0      98.63  215.00000   
8110  2017         425000      12000  0.287206   998.0      67.04   90.00000   
8111  2014         425000      50000  0.320691  1364.0      67.06  170.00000   
8112  2018         746000      24000  0.331702  1498.0      98.63  215.00000   
8113  2010         425000     129000  0.174008  2494.0     102.00  200.05464   
8114  2011         200000      73000  0.244933   796.0      46.30   62.00000   
8115  1997          40000     120000  0.200174   796.0      37.00   59.00000   
8116  

In [78]:
df.reset_index(drop=True, inplace=True)

In [79]:
df

year  selling_price  km_driven   mileage  engine  max_power     torque  \
0     2014         450000     145500  0.318108  1248.0      74.00  190.00000   
1     2014         370000     120000  0.287384  1498.0     103.52  250.00000   
2     2006         158000     140000  0.220067  1497.0      78.00  124.54382   
3     2010         225000     127000  0.312670  1396.0      90.00  219.66784   
4     2007         130000     120000  0.200174  1298.0      88.20  112.77590   
5     2017         440000      45000  0.250404  1197.0      81.86  113.75000   
6     2007          96000     175000  0.423501  1061.0      57.50   76.49148   
7     2001          45000       5000  0.200174   796.0      37.00   59.00000   
8     2011         350000      90000  0.320691  1364.0      67.10  170.00000   
9     2013         200000     169000  0.271887  1399.0      68.10  160.00000   
10    2014         500000      68000  0.258428  1461.0     108.45  248.00000   
11    2005          92000     100000  0.215094   993.0      60.00   78.00000   
12    2009         280000     140000  0.262371  1248.0      73.90  190.00000   
13    2009         180000      90000  0.234987  1061.0      67.00   84.00000   
14    2016         400000      40000  0.225662  1198.0      82.00  115.00000   
15    2016         778000      70000  0.333333  1248.0      88.50  200.00000   
16    2012         500000      53000  0.312670  1396.0      90.00  219.66784   
17    2002         150000      80000  0.244933   796.0      46.30   62.00000   
18    2016         680000     100000  0.306417  1396.0      88.73  219.70000   
19    2011         174000     100000  0.285481  1461.0      64.10  160.00000   
20    2017         950000      50000  0.346656  1498.0      98.60  200.00000   
21    2015         525000      40000  0.361474  1248.0      74.00  190.00000   
22    2012         600000      72000  0.292278  1248.0      88.80  200.00000   
23    2018         500000      35000  0.252393  1199.0      83.81  114.00000   
24    2016         575000      45000  0.266070  1197.0      83.10  115.00000   
25    2017         275000      28000  0.307099   796.0      47.30   69.00000   
26    2013         300000      70000  0.247417  1248.0      73.80  172.50000   
27    2009         220000     120000  0.234987  1061.0      67.00   84.00000   
28    2018         254999      25000  0.208877   796.0      34.20   59.00000   
29    2017         670000      70000  0.330343  1248.0      88.50  200.00000   
...    ...            ...        ...       ...     ...        ...        ...   
7876  2018         880000      65000  0.312670  1498.0      98.96  205.00000   
7877  2009         307000     100000  0.241979  1248.0      75.00  190.00000   
7878  2013         750000     120000  0.205275  2179.0     140.00  330.00000   
7879  2018         800000      85000  0.292278  1497.0     108.50  260.00000   
7880  2012         450000      70000  0.275965  1248.0      75.00  197.00000   
7881  2011         450000     128000  0.303426  1582.0     126.32  259.80000   
7882  2006         160000      70000  0.210121  1497.0     100.00  132.38910   
7883  2004         135000     120000  0.161631  1343.0      90.00  110.81458   
7884  2012         450000     128000  0.303426  1582.0     126.32  259.80000   
7885  2013         325000     100000  0.278004  1461.0      83.80  200.00000   
7886  2019        1575000      20000  0.241979  1493.0     113.40  250.00000   
7887  2018         750000      24000  0.331702  1498.0      98.63  215.00000   
7888  2017         425000      12000  0.287206   998.0      67.04   90.00000   
7889  2014         425000      50000  0.320691  1364.0      67.06  170.00000   
7890  2018         746000      24000  0.331702  1498.0      98.63  215.00000   
7891  2010         425000     129000  0.174008  2494.0     102.00  200.05464   
7892  2011         200000      73000  0.244933   796.0      46.30   62.00000   
7893  1997          40000     120000  0.200174   796.0      37.00   59.00000   
7894  

In [80]:
kf=KFold(n_splits=5)

In [81]:
X=df.drop('selling_price', axis=1)
y=df['selling_price']

In [82]:
for i,j in kf.split(X):
    print(i,j)

[1582 1583 1584 ... 7903 7904 7905] [   0    1    2 ... 1579 1580 1581]
[   0    1    2 ... 7903 7904 7905] [1582 1583 1584 ... 3160 3161 3162]
[   0    1    2 ... 7903 7904 7905] [3163 3164 3165 ... 4741 4742 4743]
[   0    1    2 ... 7903 7904 7905] [4744 4745 4746 ... 6322 6323 6324]
[   0    1    2 ... 6322 6323 6324] [6325 6326 6327 ... 7903 7904 7905]


In [83]:
for train_index, test_index in kf.split(X):
    X_train, X_test = X.loc[train_index],X.loc[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [84]:
train_rmse_total = []
test_rmse_total = []

In [87]:
for train_index, test_index in kf.split(X):
    X_train, X_test = X.loc[train_index],X.loc[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    model = RandomForestRegressor(random_state=100)
    model.fit(X_train, y_train)
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)
    
    train_rmse= mean_squared_error(y_train, train_pred)**0.5 
    test_rmse= mean_squared_error(y_test, test_pred)**0.5
    
    train_rmse_total.append(train_rmse)
    test_rmse_total.append(test_rmse)
    

In [88]:
train_rmse_total

[63077.94657794671,
 63077.94657794671,
 63077.94657794671,
 65600.89151855985,
 70286.92790264332,
 63126.25846374735,
 69548.52572421309]

In [89]:
print('train_rmse:',sum(train_rmse_total)/5, 'test_rmse:',sum(test_rmse_total)/5)

train_rmse: 91559.28866860076 test_rmse: 146383.47358831842


In [91]:
train_rmse_total = []
test_rmse_total = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X.loc[train_index],X.loc[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    model = RandomForestRegressor(n_estimators=300, max_depth = 50, min_samples_split = 5, min_samples_leaf=1, n_jobs=-1 ,random_state=100)
    model.fit(X_train, y_train)
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)
    
    train_rmse= mean_squared_error(y_train, train_pred)**0.5 
    test_rmse= mean_squared_error(y_test, test_pred)**0.5
    
    train_rmse_total.append(train_rmse)
    test_rmse_total.append(test_rmse)
    


In [92]:
print('train_rmse:',sum(train_rmse_total)/5, 'test_rmse:',sum(test_rmse_total)/5)

train_rmse: 66762.87840477741 test_rmse: 142206.09679835328
